#pragma once

enum SCENE { SCENE_LOGO, SCENE_SR, SCENE_NS, SCENE_END };
enum RESOURCETYPE { RESOURCE_STATIC, RESOURCE_LOGO, RESOURCE_SR, RESOURCE_NS, RESOURCE_END };

//For. Server
enum SOCKET_TYPE { SOCKET_LOGINCHATTING, SOCKET_GAMECONTENTS, SOCKET_END };